server:
  port: 2024
spring:
  application:
    name: ${SPRING_APP_NAME:ebsec}
  security:
    user:
      name: ${SECURITY_USERNAME:demoUser}
      password: ${SECURITY_PASSWORD:demoPwd}
logging:
  #level:
    #org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}